// Generated by CoffeeScript 1.7.1
(function() {
  var ASANAS, Question, Trivia, app;

  ASANAS = window._ASANAS;

  app = angular.module('asanaTrivia', ['ngRoute']);

  Question = (function() {
    function Question(candidates, answer) {
      var incorrect;
      this.answer = answer;
      incorrect = _.without(candidates, this.answer);
      this.options = _.shuffle(_.sample(incorrect, 3).concat([this.answer]));
    }

    return Question;

  })();

  Trivia = (function() {
    function Trivia(question_asanas, answer_candidates) {
      this.question_asanas = question_asanas;
      this.answer_candidates = answer_candidates;
      this.order = _.shuffle(this.question_asanas);
      this.total = this.question_asanas.length;
      this.answered = 0;
      this.correct = 0;
      this.ongoing = true;
      this.next();
    }

    Trivia.prototype.next = function() {
      if (this.order.length > 0) {
        return this.question = new Question(this.answer_candidates, this.order.pop());
      } else {
        return this.ongoing = false;
      }
    };

    Trivia.prototype.choose = function(answer) {
      if (!this.ongoing) {
        return;
      }
      this.answered++;
      if (answer.name === this.question.answer.name) {
        this.correct++;
      }
      return this.next();
    };

    return Trivia;

  })();

  app.service('triviaService', function() {
    return {
      restart: function() {
        return this.trivia = new Trivia(_.sample(ASANAS, 5), ASANAS);
      }
    };
  });

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'tpl/home.html',
        controller: 'Home'
      }).when('/trivia', {
        templateUrl: 'tpl/trivia.html',
        controller: 'Trivia'
      }).when('/results', {
        templateUrl: 'tpl/results.html',
        controller: 'Results'
      }).otherwise({
        redirectTo: '/trivia'
      });
    }
  ]);

  app.controller('Home', function($scope, $location) {});

  app.controller('Trivia', [
    '$scope', '$location', 'triviaService', function($scope, $location, triviaService) {
      triviaService.restart();
      $scope.trivia = triviaService.trivia;
      return $scope.choose = function(index) {
        $scope.trivia.choose($scope.trivia.question.options[index]);
        if (!$scope.trivia.ongoing) {
          return $location.path('/results');
        }
      };
    }
  ]);

  app.controller('Results', [
    '$scope', '$location', 'triviaService', function($scope, $location, triviaService) {
      if (!triviaService.trivia) {
        $location.path('/');
        return;
      }
      return $scope.trivia = triviaService.trivia;
    }
  ]);

}).call(this);
